### PR TITLE
Add support for ENABLE/FORCE RLS and RLS policies

### PR DESCRIPTION
**Pull request by steve-chavez**
This adds support for diffing the `ALTER TABLE table ENABLE/FORCE ROW LEVEL SECURITY`, this is the first part of RLS support, I'll be adding support for `CREATE POLICY` as well but for now I would like some feedback on this to see if the change in the codebase is good.

### CODE REVIEW

**Comment by chadfurman** [comment]
Can someone second this?  Pull it down, build it, see if it works for you?

**Comment by ruslantalpa** [comment]
@chadfurman although i am working with @steve-chavez on this (i asked him to develop those fixes for https://github.com/subzerocloud/devtools) i did build this branch, and i did some tests (in adition to those in this PR) on schemas with RLS and it works.

Since this PR, i discovered other bugs, related to grants on columns for views which i fixed here https://github.com/subzerocloud/apgdiff/commits/develop
and i would be happy to push them upstream but this PR needs to be merged first since i worked on a branch which contained steve's RLS  work.

**Comment by chadfurman** [comment]
merged

**Comment by ruslantalpa** [comment]
@chadfurman thanks, I'll clean up the code a little bit and create a PR next week

**Comment by chadfurman** [comment]
https://github.com/fordfrog/apgdiff/pull/210  

@ruslantalpa I'm guessing we don't need PR#210 anymore?

**Comment by ruslantalpa** [comment]
no we don't, that PR only ignored the statement, not actually supported it.
@steve-chavez PR + a few small changes from mine, fully support RLS (alter table + create policy)

**Comment by chadfurman** [comment]
great, thank you :)

**Pull request merged**
