### PR TITLE
Drop objects if exists

### PR DESCRIPTION
**Pull request by jalissonmello**
Add if exists to drop objects on method  getDropSQL

### CODE REVIEW

**Comment by jalisson** [comment]
Update Test resources

**Comment by DemonVex** [comment]
Well, I don't think we can do this for everyone. I prefer to get an explicit error if I do something wrong with my database. We may have this as command line option.

**Comment by jalissonmello** [comment]
Thanks. I will add a command line option to this option.

**Comment by chadfurman** [comment]
https://github.com/fordfrog/apgdiff/pull/192/files#diff-fece4b2dfc9ac0d464cbb6525e930a92R136

Looks like you might have added the option?  Is it a CLI flag?  Is it off by default?

There's also a great deal happening in this branch.  You've updated the dependencies, as well as changed the permissions on many files.

This PR might have a valuable feature hidden in it, but we need to get it cleaned up a bit first.

**Comment by jalissonmello** [comment]
Hi,
Yes,I added the option useIfExists as CLI flag and its off by default.  On the dependencies, I had to update because the environment that I had at my disposal at the moment, but the permissions on the files probably was by accident. 
If the code still need changes please tell me and I will be glad to help

**Comment by jalissonmello** [comment]
Hi,
Yes,I added the option useIfExists as CLI flag and its off by default.  On the dependencies, I had to update because the environment that I had at my disposal at the moment, but the permissions on the files probably was by accident. 
If the code still need changes please tell me and I will be glad to help

**Comment by chadfurman** [comment]
@jalissonmello definitely need to atleast update your PR.  I can't merge it with conflicts.

We also need atleast one more person to sign off on this.  Someone else to pull it down and make sure it compiles etc.

**Comment by jalissonmello** [comment]
I updated the code with the last alterations of the repository in the main classe with conflict 
src/main/java/cz/startnet/utils/pgdiff/PgDiff.java

I hope that with the changes, the conflict will be solved and none of the last alterations will be lost

**Comment by chadfurman** [comment]
@jalissonmello If you notice, at the bottom of this PR you should see a notice where conflicts are not resolved.

To resolve conflicts, please pull down the fordfrog:develop branch locally, merge it into your branch, and then push the resolved conflicts up on your own branch again.

**Comment by chadfurman** [comment]
Why are you modifying the readme and the changelog?

**Comment by jalissonmello** [comment]
Now the project is compiling without errors and there are not problems with the tests cases. The readme i modified only to local use and reverted to the original file.If the code still needs changes to be merged please tell me that I will do theses changes.

**Comment by chadfurman** [comment]
Hmm, thank you for taking the time to work with me on this.  So to get this merged I need to be able to review it -- there's about 350 changed files to review?  

Many of the files in this PR say things like "no changes" in the diff -- so I'm thinking at this point we need to close this PR and re-open it against the develop branch.  We need to trim all the extraneous changes.  I find it hard to believe you needed to touch 350 files to add this functionality.

Once we get this PR adequately reviewed, we can merge it.  Anyone willing to review it ahead of the reduction in the number of modified files, please feel free

**Comment by jalissonmello** [comment]
Hi, you are correct. I did not modify 350 files, maybe 100, because there a lot of test cases. I will review the changes to reduce the number of modified files and create and new pull request

**Pull request closed without merging**
