### PR TITLE
fixes for comment parsing

### LINKED ISSUE #159: Cannot parse string: COMMENT ON COLUMN
I am trying to get a diff from a schema I have and I get the next error:

Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot parse string: COMMENT ON COLUMN public.abonado.estado IS '1=activo  /  2=suspendido   /  3=suspendido y retirado  / 0=eliminado';
Expected IS at position 33 '.estado IS '1=activo'
    at cz.startnet.utils.pgdiff.parsers.Parser.expect(Parser.java:86)
    at cz.startnet.utils.pgdiff.parsers.Parser.expect(Parser.java:47)
    at cz.startnet.utils.pgdiff.parsers.CommentParser.parseColumn(CommentParser.java:255)
    at cz.startnet.utils.pgdiff.parsers.CommentParser.parse(CommentParser.java:42)
    at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:200)
    at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
    at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
    at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

Can you add support for COMMENTS or how can I help you? I am a Java developer anyway.

### PR DESCRIPTION
**Pull request by jonnio**
resolves https://github.com/fordfrog/apgdiff/issues/159 for newer pg_dump defaults

### CODE REVIEW

**Comment by elidorio** [comment]
Hello!
Where did I download the latest * .jar with implementations that are running PostgreSQL 10?
I tried to use the release version apgdiff 2.5.0-alpha.2, but is generating errors, as issue # 239 opened 10 days ago by me.
Thank you.

**Comment by matthewkmacdonald** [comment]
This looks like a good way to address the changes in pg_dump semantics which were recently introduced.  +1 for adding tests for it too!

**Comment by valorize** [comment]
@chadfurman are you able to merge this into develop?

**Comment by valoricDe** [comment]
In order to get my fresh schema dump working with https://github.com/valorize/postgres-schema-updater I had to also merge https://github.com/fordfrog/apgdiff/pull/228 into develop.
As the tests are all green I'm going to be bold and will merge this into `fordfrog:develop`.

**Pull request merged**
